apiVersion: v1
kind: ConfigMap
metadata:
  name: ocp-auth-server
data:
  login.config: |
    OpenshiftLogin {
      org.apache.activemq.artemis.spi.core.security.jaas.KubernetesLoginModule required
      roleName="amq-users"
      roleClaim="roles"
      serviceAccountToken="/var/run/secrets/kubernetes.io/serviceaccount/token"
      validateCertificate=true;
      clientId="system:serviceaccount:ocp-auth-server:java.security.auth.login.config-sa";
    };
