apiVersion: v1
kind: ConfigMap
metadata:
  name: ocp-auth-server
data:
  login.config: |
    KubernetesLogin {
      org.apache.activemq.artemis.spi.core.security.jaas.KubernetesLoginModule required
      roleName="amq-users"
      serviceAccountToken="/var/run/secrets/kubernetes.io/serviceaccount/token"
      validateCertificate=true;
    };
