apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ocp-amq-broker

labels:
  - includeSelectors: true
    pairs:
      app: ocp-amq-broker

resources:
  - configmap.yaml
  - pvc.yaml
  - route.yaml
  - secret.yaml
#  - service.yaml
  - statefulset.yaml
