apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ocp-auth-server

labels:
  - includeSelectors: true
    pairs:
      app: ocp-auth-server

resources:
  - pvc.yaml
  - route.yaml
  - secret.yaml
  - service.yaml
  - statefulset.yaml
