kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ocp-auth-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem
