apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ocp-auth-client-role
rules:
  - apiGroups: [""]
    resources:
      - "pods"
      - "services"
      - "endpoints"
    verbs:
      - "get"
      - "list"
      - "watch"

  - apiGroups: [""]
    resources:
      - "secrets"
    verbs:
      - "get"

  - apiGroups: [""]
    resources:
      - "configmaps"
    verbs:
      - "get"
      - "list"

  - apiGroups: [""]
    resources:
      - "pods/exec"
    verbs:
      - "create"

  - apiGroups: ["broker.amq.io"]
    resources:
      - "queues"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "send"
      - "consume"
      - "browse"