apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ocp-auth-client-rolebinding
subjects:
  - kind: ServiceAccount
    name: ocp-auth-client-sa
    namespace: ocp-auth-client
roleRef:
  kind: Role
  name: ocp-auth-client-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ocp-auth-server-rolebinding
subjects:
  - kind: ServiceAccount
    name: ocp-auth-server-sa
    namespace: ocp-auth-server
roleRef:
  kind: Role
  name: ocp-auth-client-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ocp-auth-server-rolebinding
subjects:
  - kind: ServiceAccount
    name: user-sa
    namespace: ocp-auth-server
roleRef:
  kind: Role
  name: ocp-auth-client-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ocp-auth-server-rolebinding
subjects:
  - kind: ServiceAccount
    name: admin-sa
    namespace: ocp-auth-server
roleRef:
  kind: Role
  name: ocp-auth-client-role
  apiGroup: rbac.authorization.k8s.io
