apiVersion: v1
kind: Secret
metadata:
  name: ocp-auth-server
type: Opaque
stringData:
  AMQ_NAME: broker
  AMQ_USER: redhat
  AMQ_PASSWORD: redhat
---
apiVersion: v1
kind: Secret
metadata:
  name: ocp-auth-server-login
type: Opaque
data:
  login.config: |
    OpenshiftLogin {
      org.apache.activemq.artemis.spi.core.security.jaas.KubernetesLoginModule required
      roleName="amq-users"
      roleClaim="roles"
      serviceAccountToken="/var/run/secrets/kubernetes.io/serviceaccount/token"
      validateCertificate=true;
      clientId="system:serviceaccount:ocp-auth-server:java.security.auth.login.config-sa";
    };
