apiVersion: v1
kind: Secret
metadata:
  name: ocp-auth-server
type: Opaque
stringData:
  AMQ_NAME: broker
  AMQ_USER: redhat
  AMQ_PASSWORD: redhat
---
apiVersion: v1
kind: Secret
metadata:
  name: ocp-auth-server-login
type: Opaque
data:
  login.config: |-
    T3BlbnNoaWZ0TG9naW4gewogIG9yZy5hcGFjaGUuYWN0aXZlbXEuYXJ0ZW1pcy5zcGkuY29yZS5zZWN1cml0eS5qYWFzLkt1YmVybmV0ZXNMb2dpbk1vZHVsZSByZXF1aXJlZAogIHJvbGVOYW1lPSJhbXEtdXNlcnMiCiAgcm9sZUNsYWltPSJyb2xlcyIKICBzZXJ2aWNlQWNjb3VudFRva2VuPSIvdmFyL3J1bi9zZWNyZXRzL2t1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvdG9rZW4iCiAgdmFsaWRhdGVDZXJ0aWZpY2F0ZT10cnVlOwogIGNsaWVudElkPSJzeXN0ZW06c2VydmljZWFjY291bnQ6b2NwLWF1dGgtc2VydmVyOmphdmEuc2VjdXJpdHkuYXV0aC5sb2dpbi5jb25maWctc2EiOwp9Owo=
