apiVersion: v1
kind: Secret
metadata:
  name: ocp-auth-server
type: Opaque
stringData:
  AMQ_NAME: 'broker'
  AMQ_USER: 'redhat'
  AMQ_PASSWORD: 'redhat'
  AMQ_REQUIRE_LOGIN: 'true'
  AMQ_DATA_DIR: '/opt/amq/broker/data/'
---
apiVersion: v1
kind: Secret
metadata:
  name: ocp-auth-server-login
type: Opaque
data:
  login.config: |-
    LyoKICogTGljZW5zZWQgdG8gdGhlIEFwYWNoZSBTb2Z0d2FyZSBGb3VuZGF0aW9uIChBU0YpIHVuZGVyIG9uZSBvciBtb3JlCiAqIGNvbnRyaWJ1dG9yIGxpY2Vuc2UgYWdyZWVtZW50cy4gIFNlZSB0aGUgTk9USUNFIGZpbGUgZGlzdHJpYnV0ZWQgd2l0aAogKiB0aGlzIHdvcmsgZm9yIGFkZGl0aW9uYWwgaW5mb3JtYXRpb24gcmVnYXJkaW5nIGNvcHlyaWdodCBvd25lcnNoaXAuCiAqIFRoZSBBU0YgbGljZW5zZXMgdGhpcyBmaWxlIHRvIFlvdSB1bmRlciB0aGUgQXBhY2hlIExpY2Vuc2UsIFZlcnNpb24gMi4wCiAqICh0aGUgIkxpY2Vuc2UiKTsgeW91IG1heSBub3QgdXNlIHRoaXMgZmlsZSBleGNlcHQgaW4gY29tcGxpYW5jZSB3aXRoCiAqIHRoZSBMaWNlbnNlLiAgWW91IG1heSBvYnRhaW4gYSBjb3B5IG9mIHRoZSBMaWNlbnNlIGF0CiAqCiAqIGh0dHA6Ly93d3cuYXBhY2hlLm9yZy9saWNlbnNlcy9MSUNFTlNFLTIuMAogKgogKiBVbmxlc3MgcmVxdWlyZWQgYnkgYXBwbGljYWJsZSBsYXcgb3IgYWdyZWVkIHRvIGluIHdyaXRpbmcsIHNvZnR3YXJlCiAqIGRpc3RyaWJ1dGVkIHVuZGVyIHRoZSBMaWNlbnNlIGlzIGRpc3RyaWJ1dGVkIG9uIGFuICJBUyBJUyIgQkFTSVMsCiAqIFdJVEhPVVQgV0FSUkFOVElFUyBPUiBDT05ESVRJT05TIE9GIEFOWSBLSU5ELCBlaXRoZXIgZXhwcmVzcyBvciBpbXBsaWVkLgogKiBTZWUgdGhlIExpY2Vuc2UgZm9yIHRoZSBzcGVjaWZpYyBsYW5ndWFnZSBnb3Zlcm5pbmcgcGVybWlzc2lvbnMgYW5kCiAqIGxpbWl0YXRpb25zIHVuZGVyIHRoZSBMaWNlbnNlLgogKi8KCmFjdGl2ZW1xIHsKICAgb3JnLmFwYWNoZS5hY3RpdmVtcS5hcnRlbWlzLnNwaS5jb3JlLnNlY3VyaXR5LmphYXMuUHJvcGVydGllc0xvZ2luTW9kdWxlIHN1ZmZpY2llbnQKICAgICAgIGRlYnVnPWZhbHNlCiAgICAgICByZWxvYWQ9dHJ1ZQogICAgICAgb3JnLmFwYWNoZS5hY3RpdmVtcS5qYWFzLnByb3BlcnRpZXMudXNlcj0iYXJ0ZW1pcy11c2Vycy5wcm9wZXJ0aWVzIgogICAgICAgb3JnLmFwYWNoZS5hY3RpdmVtcS5qYWFzLnByb3BlcnRpZXMucm9sZT0iYXJ0ZW1pcy1yb2xlcy5wcm9wZXJ0aWVzIjsKCiAgIG9yZy5hcGFjaGUuYWN0aXZlbXEuYXJ0ZW1pcy5zcGkuY29yZS5zZWN1cml0eS5qYWFzLkd1ZXN0TG9naW5Nb2R1bGUgc3VmZmljaWVudAogICAgICAgZGVidWc9ZmFsc2UKICAgICAgIG9yZy5hcGFjaGUuYWN0aXZlbXEuamFhcy5ndWVzdC51c2VyPSJyZWRoYXQiCiAgICAgICBvcmcuYXBhY2hlLmFjdGl2ZW1xLmphYXMuZ3Vlc3Qucm9sZT0iYWRtaW4iOwoKICAgb3JnLmFwYWNoZS5hY3RpdmVtcS5hcnRlbWlzLnNwaS5jb3JlLnNlY3VyaXR5LmphYXMuS3ViZXJuZXRlc0xvZ2luTW9kdWxlIHJlcXVpcmVkCiAgICAgICBkZWJ1Zz10cnVlCiAgICAgICBvcmcuYXBhY2hlLmFjdGl2ZW1xLmphYXMua3ViZXJuZXRlcy5yb2xlPSIvb3B0L2FtcS9jb25mL3JvbGVzLnByb3BlcnRpZXMiOwp9Ow==