apiVersion: v1
kind: ServiceAccount
metadata:
  name: ocp-auth-server-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-sa
