kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ocp-auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocp-auth-server
  template:
    metadata:
      labels:
        app: ocp-auth-server
    spec:
      volumes:
        - name: broker-storage
          persistentVolumeClaim:
            claimName: ocp-auth-server
      containers:
        - name: activemq-artemis
          image: 'registry.redhat.io/amq7/amq-broker-rhel8:7.11.7-4.1740580601'
          envFrom:
            - secretRef:
              name: ocp-auth-server
          resources: {}
          volumeMounts:
            - name: broker-storage
              mountPath: /opt/amq/data/
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  serviceName: ocp-auth-server
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
