kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ocp-auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocp-auth-server
  template:
    metadata:
      labels:
        app: ocp-auth-server
    spec:
      serviceAccountName: ocp-auth-server-sa
      volumes:
        - name: broker-storage
          persistentVolumeClaim:
            claimName: ocp-auth-server
        - name: login-config
          secret:
            secretName: ocp-auth-server-login
      containers:
        - name: activemq-artemis
          image: 'registry.redhat.io/amq7/amq-broker-rhel8:7.11.7-4.1740580601'
          env:
            - name: JAVA_OPTS
              value: "-Djava.security.auth.login.config=/opt/amq/auth/login.config"
            - name: JDK_JAVA_OPTIONS
              value: "-Djava.security.auth.login.config=/opt/amq/auth/login.config"
            - name: ARTEMIS_EXTRA_ARGS
              value: "--jaas-config /opt/amq/auth/login.config"
          envFrom:
            - secretRef:
                name: ocp-auth-server
          resources: {}
          volumeMounts:
            - name: broker-storage
              mountPath: /opt/amq/data/
            - name: login-config
              mountPath: /opt/amq/auth/
              readOnly: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  serviceName: ocp-auth-server
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
