kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ocp-auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocp-auth-server
  template:
    metadata:
      labels:
        app: ocp-auth-server
    spec:
      serviceAccountName: ocp-auth-server-sa
      volumes:
        - name: broker-storage
          persistentVolumeClaim:
            claimName: ocp-auth-server
        - name: login-config
          secret:
            secretName: ocp-auth-server-login
        - name: amq-etc
          emptyDir: {}
      initContainers:
        - name: copy-login-config
          image: 'registry.redhat.io/ubi8/ubi-minimal:8.10-1179.1739286367'
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Copying login.config..."
              cp /opt/amq/conf/login.config /home/jboss/broker/etc/login.config
              ls -l /home/jboss/broker/etc/
          volumeMounts:
            - name: amq-etc
              mountPath: /home/jboss/broker/etc/
            - name: login-config
              mountPath: /opt/amq/conf/
      containers:
        - name: activemq-artemis
          image: 'registry.redhat.io/amq7/amq-broker-rhel8:7.11.7-4.1740580601'
          env:
#            - name: JAVA_ARGS
#              value: "-Djava.security.auth.login.config=/opt/amq/auth/login.config"
            - name: JAVA_OPTS
              value: "-Djava.security.auth.login.config=/home/jboss/broker/etc/login.config"
#            - name: JAVA_ARGS_APPEND
#              value: "-Djava.security.auth.login.config=/opt/amq/auth/login.config"
            - name: JDK_JAVA_OPTIONS
              value: "-Djava.security.auth.login.config=/home/jboss/broker/etc/login.config"
          envFrom:
            - secretRef:
                name: ocp-auth-server
          resources: {}
          volumeMounts:
            - name: broker-storage
              mountPath: /opt/amq/data/
#            - name: login-config
#              mountPath: /opt/amq/auth/
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  serviceName: ocp-auth-server
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
