kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: amq-activemq-ocp-client
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'amq-activemq-ocp-client:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'java:openjdk-17-ubi8'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/cziesman/amq-activemq-ocp-client.git'
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: amq-activemq-ocp-client-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: amq-activemq-ocp-client-github-webhook-secret
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial
