kind: Deployment
apiVersion: apps/v1
metadata:
  name: amq-activemq-ocp-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amq-activemq-ocp-client
  template:
    metadata:
      labels:
        app: amq-activemq-ocp-client-git
        deployment: amq-activemq-ocp-client-git
    spec:
      containers:
        - name: amq-activemq-ocp-client-git
          image: 'image-registry.openshift-image-registry.svc:5000/ocp-amq-client/amq-activemq-ocp-client-git:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
