apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocp-auth-client

labels:
  - includeSelectors: true
    pairs:
      app: ocp-auth-client

resources:
  - serviceaccount.yaml
