kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ocp-amq-broker
spec:
  to:
    kind: Service
    name: ocp-amq-broker
    weight: 100
  port:
    targetPort: web-console
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
