kind: Service
apiVersion: v1
metadata:
  name: ocp-amq-broker
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: core-messaging
      protocol: TCP
      port: 61616
      targetPort: 61616
    - name: core-messaging-tls
      protocol: TCP
      port: 61617
      targetPort: 61617
    - name: web-console
      protocol: TCP
      port: 8161
      targetPort: 8161
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
